FROM surnet/alpine-node-wkhtmltopdf:22.11.0-0.12.6-small

RUN apk add --no-cache \
    watchexec --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
    && \
    apk add --no-cache \
    just --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
    ;

WORKDIR /app
VOLUME [ "/app/output" ]
VOLUME [ "/app/src"]
COPY package.json justfile ./
RUN just install-prod

CMD ["just", "all"]